# Generated by Django 3.2.6 on 2021-09-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagname',
            new_name='tag',
        ),
    ]
