# Generated by Django 3.2.6 on 2021-09-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_tagname_tag_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tag',
            new_name='tags',
        ),
    ]
