# Generated by Django 3.2.6 on 2021-09-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_tag_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='name',
        ),
    ]
